spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wxshop
    username: root
    password: root
  main:
    log-startup-info: false
mybatis:
  config-location: classpath:db/mybatis/config.xml
